### ISSUE TITLE
Compile error on Windows-x64-MVC2019

### ISSUE THREAD

**Issue by anotatta** [juliangehring/count#82]
Compiling count v0.2.1 (C:\Users\Admin\.cargo\git\checkouts\count-19eb6cc4dc2bc9c3\f876827)
error[E0432]: unresolved import `signal_hook::SIGPIPE`
 --> src\lib.rs:6:25
  |
6 | use signal_hook::{flag, SIGPIPE};
  |                         ^^^^^^^
  |                         |
  |                         no `SIGPIPE` in the root
  |                         help: a similar name exists in the module: `SIGFPE`

**Comment by juliangehring** [comment]
Thanks for raising this.
I only targeted UNIX compatibility with this tool, and I wouldn't expect it to work on Windows systems.
